### ISSUE TITLE
What 250 in (250 / ISO) stands for?

### ISSUE THREAD

**Issue by vegetableswim** [jocelyngirard/erixposure-arduino#1]
I'm trying to make a reflected lightmeter these days, and seeking for the algorithm. I don't understand the (250 / ISO) part in your code? Could you give a clue, plz?

**Comment by jocelyngirard** [comment]
Hi @vegetableswim,

Sorry for the long delay before replying you !

The 250 is the Sekonic's constant value for incident light metering. Need to be adjusted if the enclosure or metering components differs.

More info for light meter equations and calibration values :
http://www.yedlin.net/NerdyFilmTechStuff/ExposureEquationsAndMeterCalibration.html

**Comment by vegetableswim** [comment]
Still thank you very much because your code encouraged me to seek the formula of EV and Lux ,during these years I made my own DIY light meters and they work well :D
